[package]
name = "bsan-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
serde = {version = "1.0.219", features = ["serde_derive"]}
serde_json = "1.0.140"
